use crate::tensor::{Node, TensorData};
use crate::device::EngineDevice;
use rayon::prelude::*;

#[repr(C)]
#[derive(Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
struct SgdArgs {
    lr: f32,
    clip: f32,
    size: u32,
}

pub struct SGD {
    learning_rate: f32,
    parameters: Vec<Node>, 
}

impl SGD {
    pub fn new(learning_rate: f32, parameters: Vec<Node>) -> Self {
        SGD { learning_rate, parameters }
    }

    pub fn set_learning_rate(&mut self, new_lr: f32) {
        self.learning_rate = new_lr;
    }

    /// Step 1: Wipe the slate clean
    pub fn zero_grad(&self) {
        for param in &self.parameters {
            let mut p = param.write().unwrap();
            p.grad = None;
        }
    }

    /// Step 3: Update the weights across all available hardware
    pub fn step(&self) {
        let clip_threshold = 1.0;

        for param in &self.parameters {
            let mut p = param.write().unwrap();
            
            // Explicitly dereference the lock into a standard mutable reference.
            // This allows "disjoint borrowing" of separate struct fields!
            let p_ref = &mut *p; 
            
            if let Some(grad_data) = &p_ref.grad {
                match (&mut p_ref.data, grad_data) {
                    (TensorData::Cpu(weights), TensorData::Cpu(grad)) => {
                        // 1. PURE CPU MODE
                        weights.par_iter_mut().zip(grad.par_iter()).for_each(|(w, g)| {
                            let clipped_g = g.clamp(-clip_threshold, clip_threshold);
                            *w -= clipped_g * self.learning_rate;
                        });
                    }
                    (TensorData::Gpu(weight_buf), TensorData::Cpu(grad)) => {
                        // 2. HYBRID MODE: Weights on GPU, Gradient generated by CPU fallback
                        if let EngineDevice::Gpu { device, queue } = &p_ref.device {
                            
                            let args = SgdArgs {
                                lr: self.learning_rate,
                                clip: clip_threshold,
                                size: grad.len() as u32,
                            };
                            let args_buf = device.create_buffer(&wgpu::BufferDescriptor {
                                label: Some("SGD Uniform Args"),
                                size: 12,
                                usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
                                mapped_at_creation: false,
                            });
                            queue.write_buffer(&args_buf, 0, bytemuck::bytes_of(&args));

                            let grad_size = (grad.len() * 4) as wgpu::BufferAddress;
                            let grad_buf = device.create_buffer(&wgpu::BufferDescriptor {
                                label: Some("Temporary Gradient VRAM Scratchpad"),
                                size: grad_size,
                                usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST,
                                mapped_at_creation: false,
                            });
                            queue.write_buffer(&grad_buf, 0, bytemuck::cast_slice(grad));

                            let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
                                label: Some("SGD Optimizer Shader"),
                                source: wgpu::ShaderSource::Wgsl(include_str!("sgd.wgsl").into()),
                            });

                            let bind_group_layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                                label: None,
                                entries: &[
                                    wgpu::BindGroupLayoutEntry {
                                        binding: 0,
                                        visibility: wgpu::ShaderStages::COMPUTE,
                                        ty: wgpu::BindingType::Buffer { ty: wgpu::BufferBindingType::Uniform, has_dynamic_offset: false, min_binding_size: None },
                                        count: None,
                                    },
                                    wgpu::BindGroupLayoutEntry {
                                        binding: 1,
                                        visibility: wgpu::ShaderStages::COMPUTE,
                                        ty: wgpu::BindingType::Buffer { ty: wgpu::BufferBindingType::Storage { read_only: false }, has_dynamic_offset: false, min_binding_size: None },
                                        count: None,
                                    },
                                    wgpu::BindGroupLayoutEntry {
                                        binding: 2,
                                        visibility: wgpu::ShaderStages::COMPUTE,
                                        ty: wgpu::BindingType::Buffer { ty: wgpu::BufferBindingType::Storage { read_only: true }, has_dynamic_offset: false, min_binding_size: None },
                                        count: None,
                                    },
                                ],
                            });

                            let pipeline_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
                                label: None,
                                bind_group_layouts: &[Some(&bind_group_layout)],
                                immediate_size: 0,
                            });

                            let pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
                                label: Some("SGD Compute Pipeline"),
                                layout: Some(&pipeline_layout),
                                module: &shader,
                                entry_point: Some("main"),
                                cache: None,
                                compilation_options: Default::default(),
                            });

                            let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
                                label: None,
                                layout: &bind_group_layout,
                                entries: &[
                                    wgpu::BindGroupEntry { binding: 0, resource: args_buf.as_entire_binding() },
                                    wgpu::BindGroupEntry { binding: 1, resource: weight_buf.as_entire_binding() },
                                    wgpu::BindGroupEntry { binding: 2, resource: grad_buf.as_entire_binding() },
                                ],
                            });

                            let mut encoder = device.create_command_encoder(&wgpu::CommandEncoderDescriptor { label: None });
                            {
                                let mut cpass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor { label: None, timestamp_writes: None });
                                cpass.set_pipeline(&pipeline);
                                cpass.set_bind_group(0, &bind_group, &[]);
                                
                                let workgroups = (grad.len() as u32).div_ceil(256);
                                cpass.dispatch_workgroups(workgroups, 1, 1);
                            }
                            queue.submit(Some(encoder.finish()));
                        } else {
                            unreachable!()
                        }
                    }
                    (TensorData::Gpu(weight_buf), TensorData::Gpu(grad_buf)) => {
                        // 3. PURE GPU MODE: Execute the shader natively using the existing VRAM buffers
                        if let EngineDevice::Gpu { device, queue } = &p_ref.device {
                            let size = (weight_buf.size() / 4) as u32;
                            let args = SgdArgs {
                                lr: self.learning_rate,
                                clip: clip_threshold,
                                size,
                            };
                            
                            let args_buf = device.create_buffer(&wgpu::BufferDescriptor {
                                label: Some("SGD Uniform Args"),
                                size: 12,
                                usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
                                mapped_at_creation: false,
                            });
                            queue.write_buffer(&args_buf, 0, bytemuck::bytes_of(&args));

                            let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
                                label: Some("SGD Optimizer Shader"),
                                source: wgpu::ShaderSource::Wgsl(include_str!("sgd.wgsl").into()),
                            });

                            let bind_group_layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                                label: None,
                                entries: &[
                                    wgpu::BindGroupLayoutEntry {
                                        binding: 0,
                                        visibility: wgpu::ShaderStages::COMPUTE,
                                        ty: wgpu::BindingType::Buffer { ty: wgpu::BufferBindingType::Uniform, has_dynamic_offset: false, min_binding_size: None },
                                        count: None,
                                    },
                                    wgpu::BindGroupLayoutEntry {
                                        binding: 1,
                                        visibility: wgpu::ShaderStages::COMPUTE,
                                        ty: wgpu::BindingType::Buffer { ty: wgpu::BufferBindingType::Storage { read_only: false }, has_dynamic_offset: false, min_binding_size: None },
                                        count: None,
                                    },
                                    wgpu::BindGroupLayoutEntry {
                                        binding: 2,
                                        visibility: wgpu::ShaderStages::COMPUTE,
                                        ty: wgpu::BindingType::Buffer { ty: wgpu::BufferBindingType::Storage { read_only: true }, has_dynamic_offset: false, min_binding_size: None },
                                        count: None,
                                    },
                                ],
                            });

                            let pipeline_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
                                label: None,
                                bind_group_layouts: &[Some(&bind_group_layout)],
                                immediate_size: 0,
                            });

                            let pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
                                label: Some("SGD Compute Pipeline"),
                                layout: Some(&pipeline_layout),
                                module: &shader,
                                entry_point: Some("main"),
                                cache: None,
                                compilation_options: Default::default(),
                            });

                            let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
                                label: None,
                                layout: &bind_group_layout,
                                entries: &[
                                    wgpu::BindGroupEntry { binding: 0, resource: args_buf.as_entire_binding() },
                                    wgpu::BindGroupEntry { binding: 1, resource: weight_buf.as_entire_binding() },
                                    wgpu::BindGroupEntry { binding: 2, resource: grad_buf.as_entire_binding() },
                                ],
                            });

                            let mut encoder = device.create_command_encoder(&wgpu::CommandEncoderDescriptor { label: None });
                            {
                                let mut cpass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor { label: None, timestamp_writes: None });
                                cpass.set_pipeline(&pipeline);
                                cpass.set_bind_group(0, &bind_group, &[]);
                                
                                let workgroups = size.div_ceil(256);
                                cpass.dispatch_workgroups(workgroups, 1, 1);
                            }
                            queue.submit(Some(encoder.finish()));
                        } else {
                            unreachable!()
                        }
                    }
                    _ => panic!("Hardware deployment conflict: Cannot mix CPU weights with GPU gradients unless hybrid mode is active."),
                }
            }
        }
    }
}